src/objects/API_Endpoint__c.object
<CustomObject>
    <description>API Version Endpoints that can be accessed to interact with your Org through GET, PUT, POST, PATCH or DELETE methods</description>
    <fields>
        <fullName>API_Parent_Endpoint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Parent API Endpoint for this Endpoint</description>
        <label>API Parent Endpoint</label>
        <referenceTo>API_Endpoint__c</referenceTo>
        <relationshipLabel>API Child Endpoints</relationshipLabel>
        <relationshipName>API_Endpoints</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>API_Version__c</fullName>
        <label>API Version</label>
        <referenceTo>API_Version__c</referenceTo>
        <relationshipName>APIs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to Activate the API</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Allowed_Methods__c</fullName>
        <description>Allowed HTTP Methods for the API</description>
        <label>Allowed Methods</label>
        <required>true</required>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>HTTP_Method</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>ETag_Datetime_Field__c</fullName>
        <description>Field used to calculate ETags. Must be Datetime field.</description>
        <label>ETag Datetime Field</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Include_in_Parent_GET__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Include this Endpoint in the GET request of the Parent Endpoint</description>
        <label>Include in Parent GET</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Label__c</fullName>
        <description>Singular Label for the API Endpoint</description>
        <label>Label</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_SObject_Id_Field__c</fullName>
        <description>Field that should be used by the API Endpoint to reference to its Parent</description>
        <label>Parent SObject Id Field</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SObject_API_Name__c</fullName>
        <description>The SObject API Name for this Endpoint, is used by Field Mappings</description>
        <label>SObject API Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SObject_Id_Field__c</fullName>
        <description>The SObject Id field used to Query the records as well as Insert / Update. Should be an Id or External Id field.</description>
        <label>SObject Id Field</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Version_Endpoint__c</fullName>
        <description>API Version Endpoint</description>
        <formula>&apos;/services/apexrest/api/&apos; + API_Version__r.Name + &apos;/&apos; + Name + &apos;/&apos;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Version Endpoint</label>
        <type>Text</type>
    </fields>
    <label>API Endpoint</label>
    <nameField>
        <label>API Endpoint Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>API Endpoints</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/API_Field_Mapping__c.object
<CustomObject>
    <description>API Endpoint Field Mapping that maps SObject Field to String Field Name</description>
    <fields>
        <fullName>API_Endpoint__c</fullName>
        <description>Endpoint for the Field Mapping</description>
        <label>API Endpoint</label>
        <referenceTo>API_Endpoint__c</referenceTo>
        <relationshipLabel>API Field Mappings</relationshipLabel>
        <relationshipName>API_Field_Mappings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Allowed_Methods__c</fullName>
        <description>Allowed HTTP Methods for this Field Mapping</description>
        <label>Allowed Methods</label>
        <required>true</required>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>HTTP_Method</valueSetName>
        </valueSet>
    </fields>
    <label>API Field Mapping</label>
    <nameField>
        <displayFormat>AFM-{0000000}</displayFormat>
        <label>API Field Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>API Field Mappings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/API_Log_Entry__c.object
<CustomObject>
    <description>Log Entry for access or error per API Endpoint call</description>
    <fields>
        <fullName>API_Endpoint__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>API Endpoint that was accessed</description>
        <label>API Endpoint</label>
        <referenceTo>API_Endpoint__c</referenceTo>
        <relationshipLabel>API Log Entries</relationshipLabel>
        <relationshipName>API_Log_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>API_Version__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>API Version that was accessed</description>
        <label>API Version</label>
        <referenceTo>API_Version__c</referenceTo>
        <relationshipLabel>API Log Entries</relationshipLabel>
        <relationshipName>API_Log_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HTTP_Method__c</fullName>
        <description>HTTP Method that was used to access the API</description>
        <label>HTTP Method</label>
        <length>6</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Remote_Address__c</fullName>
        <description>Remote Address (IP) from the requestor</description>
        <label>Remote Address</label>
        <length>15</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status_Code__c</fullName>
        <description>HTTP Response Code</description>
        <label>Status Code</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>API Log Entry</label>
    <nameField>
        <displayFormat>ALE-{0000000}</displayFormat>
        <label>API Log Entry Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>API Log Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/API_Version__c.object
<CustomObject>
    <description>Custom Object for API Versions Master-Detail to API Policies, Endpoints and Log Entries</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag to Activate API</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Allowed_Content_Types__c</fullName>
        <description>Allowed Content Types for the API Version. Content Type is required to respond.</description>
        <label>Allowed Content Types</label>
        <required>true</required>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>JSON</fullName>
                    <default>true</default>
                    <label>JSON</label>
                </value>
                <value>
                    <fullName>XML</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Authentication_Required__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Flag to control Authentication Policy for the API Version</description>
        <label>Authentication Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Enforce_Access_Limit_Policy__c</fullName>
        <description>If we have more than zero access limit policies then we are going to enforce access limits.</description>
        <formula>Access_Limit_Policy_Count__c &gt; 0</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Enforce Access Limit Policy</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Enforce_ETag_Header__c</fullName>
        <defaultValue>false</defaultValue>
        <description>When flagged the API Version will require &quot;ETag&quot; or &quot;If-None-Match&quot; headers to be present on each request</description>
        <label>Enforce ETag Header</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Enforce_Restrictive_Time_Policy__c</fullName>
        <description>If we have more than zero restrictive time policies then we are going to enforce restrictive time.</description>
        <formula>Restrictive_Time_Policy_Count__c &gt; 0</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Enforce Restrictive Time Policy</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Enforce_Whitelist_Policy__c</fullName>
        <description>If we have more than zero whitelist policies then we are going to enforce whitelisting.</description>
        <formula>Whitelist_Policy_Count__c &gt; 0</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Enforce Whitelist Policy</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Log_API_Access__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Log API Access by creating API_Log_Entry__c records</description>
        <label>Log API Access</label>
        <type>Checkbox</type>
    </fields>
    <label>API Version</label>
    <nameField>
        <displayFormat>v{0}</displayFormat>
        <label>API Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>API Versions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/HTTP_Method.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>GET</fullName>
    </customValue>
    <customValue>
        <fullName>HEAD</fullName>
    </customValue>
    <customValue>
        <fullName>PUT</fullName>
    </customValue>
    <customValue>
        <fullName>POST</fullName>
    </customValue>
    <customValue>
        <fullName>PATCH</fullName>
    </customValue>
    <customValue>
        <fullName>DELETE</fullName>
    </customValue>
    <masterLabel>HTTP Method</masterLabel>
</GlobalValueSet>

src/classes/RestFrameworkUtils.cls
/**
* @author Tiaan Swart (tiaan@cloudinit.nz)
* @date 2018-06-16
* @description 
*
* CHANGE LOG
* 2018-06-16 - Initial setup
**/
global with sharing class RestFrameworkUtils {

    /**
    *   @author Tiaan Swart (tiaan@cloudinit.nz)
    *   @description Get the API Version from it's Name
    *   @return API Version
    **/
    public static API_Version__c getApiVersion(String apiVersion)
    {
        // Find the API version
        List<API_Version__c> theApiVersions = [SELECT Name, Authentication_Required__c, Log_API_Access__c, Active__c,
                                                      Enforce_Access_Limit_Policy__c, Enforce_Restrictive_Time_Policy__c,
                                                      Enforce_Whitelist_Policy__c, Enforce_ETag_Header__c, Allowed_Content_Types__c
                                               FROM API_Version__c
                                               WHERE Name =: apiVersion
                                               LIMIT 1];

        // If we have no API Versions
        if (theApiVersions.isEmpty()) {
            throw new RestFrameworkResource.NotFoundException( 'API version \'' + apiVersion + '\' not found!' );
        }

        // Get the API Version Record
        API_Version__c theApiVersion = theApiVersions[0];

        // Check if the API Version is Active
        if (!theApiVersion.Active__c) {
            throw new RestFrameworkResource.ServiceUnavailableException('API version \''+apiVersion+'\' not active!');
        // If Auth is required Guests can not view the the API
        } else if (UserInfo.getUserType() == 'Guest' && theApiVersion.Authentication_Required__c) {
            throw new RestFrameworkResource.UnauthorizedException('Please log in to access the API.');
        // If we need ETags
        } else if (theApiVersion.Enforce_ETag_Header__c &&
                   (new Set<String>{'GET','HEAD'}).contains(RestFrameworkResource.req.httpMethod) &&
                   (!(RestFrameworkResource.req.headers.containsKey('ETag') || RestFrameworkResource.req.headers.containsKey('If-None-Match')) ||
                   ((RestFrameworkResource.req.headers.containsKey('ETag') && String.isBlank(RestFrameworkResource.req.headers.get('ETag'))) ||
                   (RestFrameworkResource.req.headers.containsKey('If-None-Match') && String.isBlank(RestFrameworkResource.req.headers.get('If-None-Match')))))
        ) {
            throw new RestFrameworkResource.ForbiddenException( 'Required \'ETag\' or \'If-None-Match\' header not found!' );
        }

        return theApiVersion;
    }

    /**
    *   @author Tiaan Swart (tiaan@cloudinit.nz)
    *   @description Get the API Version from it's Name
    *   @return API Version
    **/
    public static Map<String, API_Endpoint__c> APIEndpointsMapByName = new Map<String, API_Endpoint__c>();
    public static API_Endpoint__c getApiEndpoint(API_Version__c apiVersion, String apiEndpointName)
    {
        // Find the API Endpoints, if we have none
        if (APIEndpointsMapByName.isEmpty()) {
            List<API_Endpoint__c> theApiEndpoints = [SELECT Name, Allowed_Methods__c, SObject_API_Name__c, Version_Endpoint__c, Active__c,
                                                            Label__c, SObject_Id_Field__c, ETag_Datetime_Field__c, API_Parent_Endpoint__c,
                                                            Parent_SObject_Id_Field__c,
                                                            (SELECT Name FROM API_Endpoints__r WHERE Include_In_Parent_GET__c = TRUE),
                                                            (SELECT Id FROM API_Field_Mappings__r)
                                                     FROM API_Endpoint__c
                                                     WHERE API_Version__c =: apiVersion.Id
                                                     LIMIT 50000];
            // If we have API Endpoints
            if (!theApiEndpoints.isEmpty()) {
                // Map them
                for (API_Endpoint__c theApi : theApiEndpoints) {
                    APIEndpointsMapByName.put(theApi.Name, theApi);
                }
            } else {
                throw new RestFrameworkResource.NotFoundException( 'API version \'' + apiVersion + '\' has no API Endpoints!' );
            }
        }

        // Get the API Endpoint
        API_Endpoint__c theEndpoint = APIEndpointsMapByName.get(apiEndpointName);

        String apiExceptionPretext = 'API Endpoint \''+apiEndpointName+'\' for API Version \''+apiVersion.Name+'\' ';

        // If we have no Endpoint
        if (theEndpoint == null) {
            throw new RestFrameworkResource.NotFoundException( apiExceptionPretext + 'not found!' );
        // If the Endpoint is Active
        } else if (!theEndpoint.Active__c) {
            throw new RestFrameworkResource.ServiceUnavailableException(  apiExceptionPretext + 'not active!' );
        // If we are allowed to access this Endpoint through the HTTP Method
        } else if (!theEndpoint.Allowed_Methods__c.contains(RestFrameworkResource.req.httpMethod)) {
            throw new RestFrameworkResource.MethodNotAllowedException(  apiExceptionPretext + 'does not allow \''+RestFrameworkResource.req.httpMethod+'\' requests!' );
        }

        // Get the SObject Describe
        DescribeSObjectResult dsr = RestFrameworkUtils.getDsr(theEndpoint.SObject_API_Name__c);

        // Check that we have Permissions for the SObject
        if (!dsr.isAccessible()) {
            throw new RestFrameworkResource.ForbiddenException('Required permission (IsAccessible) for SObjectType \''+theEndpoint.SObject_API_Name__c+'\' missing.');
        }

        return theEndpoint;
    }

    /**
    *   @author Tiaan Swart (tiaan@cloudinit.nz)
    *   @description Get the Access Count of the Current User based on Params, only successful access counts.
    *   @return Integer access count
    **/
    @TestVisible
    private static Integer getAccessCount(String httpMethod, String remoteAddress, Id theApiVersionId, Id theApiEndpointId, Datetime startDatetime)
    {
        Id userId = UserInfo.getUserId();
        return Database.countQuery('SELECT count() ' +
                'FROM API_Log_Entry__c ' +
                'WHERE API_Version__c =: theApiVersionId ' +
                (String.isNotBlank(theApiEndpointId) ? 'AND API_Endpoint__c =: theApiEndpointId ' : '') +
                'AND ' + (UserInfo.getUserType() == 'Guest' ? 'Remote_Address__c =: remoteAddress' : '(CreatedById =: userId OR Remote_Address__c =: remoteAddress)') + ' ' +
                'AND HTTP_Method__c =: httpMethod ' +
                'AND Status_Code__c < 400 AND (CreatedDate >= :startDatetime AND CreatedDate < TOMORROW)');
    }

    /**
    *   @author Tiaan Swart (tiaan@cloudinit.nz)
    *   @description Get the Access Count of the Current User based on Params, and compare against the passed limit
    *                Add remaining Limit Header or throw Exception
    **/
    public static void checkAccessCount(Id theApiVersionId, Id theApiEndpointId, Datetime startDatetime,
            Decimal accessLimit, String limitDescription)
    {
        // Get the Access Count
        Integer accessCount = getAccessCount(
            RestFrameworkResource.req.httpMethod,
            RestFrameworkResource.req.remoteAddress,
            theApiVersionId,
            theApiEndpointId,
            startDatetime
        );

        // And we have passed the limit
        if (accessLimit < accessCount) {

            throw new RestFrameworkResource.TooManyRequestsException(
                String.format(
                    'Access not allowed! {0} {1} access limit of {2} exceeded: {3}.',
                    new String[] {
                        RestFrameworkResource.req.httpMethod,
                        limitDescription,
                        String.valueOf(accessLimit),
                        String.valueOf(accessCount)
                    }
                )
            );

        }

        // Add Remaining Access Limit Header
        RestFrameworkResource.res.addHeader('Remaining-Access-Limit-'+limitDescription, String.valueOf(accessLimit - accessCount - 1));
    }

    /**
    *   @author Tiaan Swart (tiaan@cloudinit.nz)
    *   @description Get the DescribeSObjectResult and store it in a Map for Caching
    *   @return DescribeSObjectResult
    **/
    private static Map<String, DescribeSObjectResult> dsrBySObjectName = new Map<String, DescribeSObjectResult>();
    public static DescribeSObjectResult getDsr(String SObjectTypeName)
    {
        // If we have the cached value
        if (dsrBySObjectName != null && dsrBySObjectName.containsKey(SObjectTypeName)) {
            return dsrBySObjectName.get(SObjectTypeName);
        }
        // Else get the Global describe
        Map<String, Schema.SObjectType> gd = Schema.getGlobalDescribe();
        if (!gd.containsKey(SObjectTypeName)) {
            throw new RestFrameworkResource.NotFoundException( 'SObjectType \''+SObjectTypeName+'\' not found!' );
        }
        // Get the dsr and add it to the cache
        dsrBySObjectName.put(SObjectTypeName, gd.get(SObjectTypeName).getDescribe());
        return dsrBySObjectName.get(SObjectTypeName);
    }

    /**
    *   @author Tiaan Swart (tiaan@cloudinit.nz)
    *   @description Get the Fields for an SObject and store it in a Map for Caching
    *   @return List of string Fields
    **/
    public static Map<String, Map<String, SObjectField>> fieldsBySObjectName = new Map<String, Map<String, SObjectField>>();
    public static List<String> getSObjectFieldsList(String SObjectTypeName)
    {
        // If we have the cached value
        if (fieldsBySObjectName != null && fieldsBySObjectName.containsKey(SObjectTypeName)) {
            return new List<String>(fieldsBySObjectName.get(SObjectTypeName).keySet());
        }
        // Get the dsr
        DescribeSObjectResult dsr = getDsr(SObjectTypeName);
        // Get the fields and add it to the cache
        fieldsBySObjectName.put(SObjectTypeName, dsr.fields.getMap());
        return new List<String>(fieldsBySObjectName.get(SObjectTypeName).keySet());
    }

    /**
    *   @author Tiaan Swart (tiaan@cloudinit.nz)
    *   @description Get the Field for an SObject
    *   @return SObjectField
    **/
    public static SObjectField getSObjectField(String SObjectTypeName, String SObjectFieldName)
    {
        // If we have the cached value
        if (fieldsBySObjectName != null && !fieldsBySObjectName.get(SObjectTypeName).containsKey(SObjectFieldName)) {
            throw new RestFrameworkResource.NotFoundException( 'SObjectField \''+SObjectFieldName+'\' for SObjectType \''+SObjectTypeName+'\' not found!' );
        }
        return fieldsBySObjectName.get(SObjectTypeName).get(SObjectFieldName);
    }

    /**
    *   @author Tiaan Swart (tiaan@cloudinit.nz)
    *   @description Build a Query with specified params
    *   @return List of SObjects
    **/
    public static String buildSOQL(List<String> fields, String sObjectName, String idField, String recordId, String customCondition)
    {
        // Select using all the fields
        return String.format(
                'SELECT {0} FROM {1}{2}{3}{4}{5}{6}{7}{8}',
                new String[] {
                        String.join(fields, ','),
                        sObjectName,
                        (String.isNotBlank(idField) || String.isNotBlank(recordId)) || String.isNotBlank(customCondition) ? ' WHERE ' : '',
                        String.isNotBlank(idField) ? idField : '',
                        String.isNotBlank(idField) ? (String.isNotBlank(recordId) ? '=' : '!=') : '',
                        String.isNotBlank(idField) ? (String.isNotBlank(recordId) ? '\''+recordId+'\'' : 'NULL') : '',
                        String.isNotBlank(idField) && String.isNotBlank(customCondition) ? ' AND (' : '',
                        String.isNotBlank(customCondition) ? customCondition : '',
                        String.isNotBlank(idField) && String.isNotBlank(customCondition) ? ')' : ''
                }
        );
    }

    /**
    *   @author Tiaan Swart (tiaan@cloudinit.nz)
    *   @description Get the Records for a GET or HEAD request
    *   @return List of SObjects
    **/
    public static List<SObject> getResults(List<String> fields, String sObjectName, String idField, String recordId,
            String customCondition)
    {
        // Get results
        List<SObject> results = Database.query( buildSOQL(fields, sObjectName, idField, recordId, customCondition) );

        // If we had an Id we expect a result
        if (String.isNotBlank(recordId) && results.isEmpty()) {

            throw new RestFrameworkResource.NotFoundException('Record with Id \''+recordId+'\' Not Found!');

        }

        // Return the results
        return results;
    }

    /**
    *   @author Tiaan Swart (tiaan@cloudinit.nz)
    *   @description Get an Epoc Long from a Datetime object
    *   @return Epoc Long String
    **/
    public static String getEpocLongStr(Object dateTimeObj)
    {
        return String.valueOf(((DateTime) JSON.deserialize((String) dateTimeObj, DateTime.class)).getTime());
    }

    /**
    *   @author Tiaan Swart (tiaan@cloudinit.nz)
    *   @description Get an ETag value from passed value
    *   @return String MD5 ETag
    **/
    private static String etagKey = 'hgdhdhhdjfh12ehsn';
    private static String etagSecret = 'DNf32sdsj747dhkjd8893jjjdjds7jjk';
    public static String getETagVal(String etagValue)
    {
        return EncodingUtil.convertToHex(Crypto.generateDigest('MD5', Blob.valueOf(etagKey + etagSecret + etagValue)));
    }

    /**
    *   @author Tiaan Swart (tiaan@cloudinit.nz)
    *   @description Build an attributes map for a record
    **/
    public static void buildAttributesMappings(Map<String, Object> recordMap, API_Endpoint__c theApiEndpoint, List<String> childETags)
    {
        // Add the attributes mapping
        recordMap.put(
            'attributes',
            new Map<String, String>{
                'type' => theApiEndpoint.Label__c,
                'url' => theApiEndpoint.Version_Endpoint__c + String.valueOf(recordMap.get(theApiEndpoint.SObject_Id_Field__c)),
                'etag' => getETagVal(
                    getEpocLongStr(recordMap.get(theApiEndpoint.ETag_Datetime_Field__c))
                    + String.join(childETags, '')
                )
            }
        );
    }

    /**
    *   @author Tiaan Swart (tiaan@cloudinit.nz)
    *   @description String Final Etag, Prepared by the Build Record Map
    **/
    private static String finalEtag = '';

    /**
    *   @author Tiaan Swart (tiaan@cloudinit.nz)
    *   @description Build the record map with attributes and custom mappings
    **/
    public static void buildRecordMap(List<Object> resultsMap, API_Endpoint__c theApiEndpoint, Map<String, API_Endpoint__c> childRelationshipMap,
            Boolean isChildEndpoint)
    {
        // For each record
        for (Object record : resultsMap) {

            // Get the record as a Map
            Map<String, Object> recordMap = (Map<String, Object>) record;

            // List to keep the Child ETags
            List<String> childETags = new List<String>();

            // If we have child relationships they need to be built as well
            for (String childRelationshipName : childRelationshipMap.keySet()) {

                // Get the Endpoint
                API_Endpoint__c childEndpoint = childRelationshipMap.get(childRelationshipName);

                // Get the Child Records Map
                Map<String, Object> childRecordsMap = (Map<String, Object>) recordMap.get(childRelationshipName);

                // Remove the "done" key value pair
                childRecordsMap.remove('done');

                // Get the records
                List<Object> childRecords = (List<Object>) childRecordsMap.get('records');

                // Now build the record Map from the actual records
                buildRecordMap(childRecords, childEndpoint, new Map<String, API_Endpoint__c>(), true);

                // Gather the ETags
                for (Object childRecord : childRecords) {

                    // Get the attributes mapping
                    Map<String, String> attributesMapping = (Map<String, String>) ((Map<String, Object>) childRecord).get('attributes');

                    // Add the ETag
                    childETags.add(attributesMapping.get('etag'));

                }

                // Replace Child Relationship Name with Endpoint Name
                recordMap.put(childEndpoint.Name, recordMap.get(childRelationshipName));

                // If the Child Relationship name is different to the Child Endpoint name
                if (childEndpoint.Name != childRelationshipName)  {
                    // Remove it
                    recordMap.remove(childRelationshipName);
                }

            }

            // Add the attributes mapping
            buildAttributesMappings(recordMap, theApiEndpoint, childETags);

            // If this is not a child endpoint
            if (!isChildEndpoint) {

                // Get the attributes mapping
                Map<String, String> attributesMapping = (Map<String, String>) ((Map<String, Object>) recordMap).get('attributes');

                // Add the ETag
                finalEtag += (String.isBlank(finalEtag) ? '' : ',') + attributesMapping.get('etag');
            }

        }
    }

    /**
    *   @author Tiaan Swart (tiaan@cloudinit.nz)
    *   @description Get a combination of all etags generated as a final etag
    *   @return String MD5 ETag
    **/
    public static String getFinalETag()
    {
        // Get a list of ETags
        if (String.isNotBlank(finalEtag)) {
            List<String> etagList = finalEtag.split(',');
            // If we only have one etag
            if (etagList.size() == 1) {
                // Return that one
                return etagList[0];
            }
            // Else create a combination ETag
            return getETagVal( String.join(etagList, '') );
        }
        return null;
    }

    /**
    *   @author Tiaan Swart (tiaan@cloudinit.nz)
    *   @description Get a String output of Execution Governors and Limits
    *   @return String of Limits used
    **/
    public static String getLimits()
    {
        return  'AggregateQueries: ' + Limits.getAggregateQueries() + ' / ' + Limits.getLimitAggregateQueries() + ((Limits.getAggregateQueries()/Limits.getLimitAggregateQueries()) > 0.5 ? ' *** Close to limit *** ' : '') + '\n' +
                'Callouts: ' + Limits.getCallouts() + ' / ' + Limits.getLimitCallouts() + ((Limits.getCallouts()/Limits.getLimitCallouts()) > 0.5 ? ' *** Close to limit *** ' : '') + '\n' +
                'CpuTime: ' + Limits.getCpuTime() + ' / ' + Limits.getLimitCpuTime() + ((Limits.getCpuTime()/Limits.getLimitCpuTime()) > 0.5 ? ' *** Close to limit *** ' : '') + '\n' +
                'DatabaseTime: ' + Limits.getDatabaseTime() + ' / ' + Limits.getLimitDatabaseTime() + '\n' +
                'DmlRows: ' + Limits.getDmlRows() + ' / ' + Limits.getLimitDmlRows() + ((Limits.getDmlRows()/Limits.getLimitDmlRows()) > 0.5 ? ' *** Close to limit *** ' : '') + '\n' +
                'DmlStatements: ' + Limits.getDmlStatements() + ' / ' + Limits.getLimitDmlStatements() + ((Limits.getDmlStatements()/Limits.getLimitDmlStatements()) > 0.5 ? ' *** Close to limit *** ' : '') + '\n' +
                'EmailInvocations: ' + Limits.getEmailInvocations() + ' / ' + Limits.getLimitEmailInvocations() + ((Limits.getEmailInvocations()/Limits.getLimitEmailInvocations()) > 0.5 ? ' *** Close to limit *** ' : '') + '\n' +
                'FindSimilarCalls: ' + Limits.getFindSimilarCalls() + ' / ' + Limits.getLimitFindSimilarCalls() + ((Limits.getFindSimilarCalls()/Limits.getLimitFindSimilarCalls()) > 0.5 ? ' *** Close to limit *** ' : '') + '\n' +
                'FutureCalls: ' + Limits.getFutureCalls() + ' / ' + Limits.getLimitFutureCalls() + ((Limits.getFutureCalls()/Limits.getLimitFutureCalls()) > 0.5 ? ' *** Close to limit *** ' : '') + '\n' +
                'HeapSize: ' + Limits.getHeapSize() + ' / ' + Limits.getLimitHeapSize() + ((Limits.getHeapSize()/Limits.getLimitHeapSize()) > 0.5 ? ' *** Close to limit *** ' : '') + '\n' +
                'MobilePushApexCalls: ' + Limits.getMobilePushApexCalls() + ' / ' + Limits.getLimitMobilePushApexCalls() + ((Limits.getMobilePushApexCalls()/Limits.getLimitMobilePushApexCalls()) > 0.5 ? ' *** Close to limit *** ' : '') + '\n' +
                'Queries: ' + Limits.getQueries() + ' / ' + Limits.getLimitQueries() + ((Limits.getQueries()/Limits.getLimitQueries()) > 0.5 ? ' *** Close to limit *** ' : '') + '\n' +
                'QueryLocatorRows: ' + Limits.getQueryLocatorRows() + ' / ' + Limits.getLimitQueryLocatorRows() + ((Limits.getQueryLocatorRows()/Limits.getLimitQueryLocatorRows()) > 0.5 ? ' *** Close to limit *** ' : '') + '\n' +
                'QueryRows: ' + Limits.getQueryRows() + ' / ' + Limits.getLimitQueryRows() + ((Limits.getQueryRows()/Limits.getLimitQueryRows()) > 0.5 ? ' *** Close to limit *** ' : '') + '\n' +
                'QueueableJobs: ' + Limits.getQueueableJobs() + ' / ' + Limits.getLimitQueueableJobs() + ((Limits.getQueueableJobs()/Limits.getLimitQueueableJobs()) > 0.5 ? ' *** Close to limit *** ' : '') + '\n' +
                'RunAs: ' + Limits.getRunAs() + ' / ' + Limits.getLimitRunAs() + ((Limits.getRunAs()/Limits.getLimitRunAs()) > 0.5 ? ' *** Close to limit *** ' : '') + '\n' +
                'SavepointRollbacks: ' + Limits.getSavepointRollbacks() + ' / ' + Limits.getLimitSavepointRollbacks() + ((Limits.getSavepointRollbacks()/Limits.getLimitSavepointRollbacks()) > 0.5 ? ' *** Close to limit *** ' : '') + '\n' +
                'Savepoints: ' + Limits.getSavepoints() + ' / ' + Limits.getLimitSavepoints() + ((Limits.getSavepoints()/Limits.getLimitSavepoints()) > 0.5 ? ' *** Close to limit *** ' : '') + '\n' +
                'SoslQueries: ' + Limits.getSoslQueries() + ' / ' + Limits.getLimitSoslQueries() + ((Limits.getSoslQueries()/Limits.getLimitSoslQueries()) > 0.5 ? ' *** Close to limit *** ' : '');
    }

}